# Generated by Django 4.2.6 on 2023-10-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_publish_bb7600_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated_at',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='blog_post_publish_2c9212_idx'),
        ),
    ]
